name: rlkit-env
channels:
    - defaults
    - https://conda.anaconda.org/kne
    - https://conda.anaconda.org/tlatorre
    - https://conda.anaconda.org/menpo
    - jjhelmus
    - soumith
dependencies:
    - python==3.5.2
    - numpy==1.11.3
    - scipy
    - path.py
    - python-dateutil
    - joblib==0.9.4
    - mako
    - ipywidgets
    - numba
    - flask
    - pybox2d
    - pygame
    - h5py
    - matplotlib
    - opencv3=3.1.0
    - scikit-learn
    - pytorch
    - torchvision
    - scikit-image
    - cuda80
    - pip:
        - git+git://github.com/pytorch/pytorch.git@v0.3.0
        # Tensorflow 1.0, GPU only
        - https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.0.1-cp35-cp35m-linux_x86_64.whl
        - Pillow
        - atari-py
        - pyprind
        - ipdb
        - boto3
        - PyOpenGL
        - nose2
        - pyzmq
        - msgpack-python
        - mujoco_py==0.5.7
        - cached_property
        - line_profiler
        - Cython
        - git+https://github.com/Theano/Theano.git@adfe319ce6b781083d8dc3200fb4481b00853791#egg=Theano
        - git+https://github.com/neocxi/Lasagne.git@484866cf8b38d878e92d521be445968531646bb8#egg=Lasagne
        - git+https://github.com/plotly/plotly.py.git@2594076e29584ede2d09f2aa40a8a195b3f3fc66#egg=plotly
        - awscli
        - git+https://github.com/openai/gym.git
        - pyglet
        - git+https://github.com/neocxi/prettytensor.git
        - jupyter
        - progressbar2
#        - chainer==1.15.0
        - cloudpickle==0.2.2
        - rospkg
        - lasagne
        - ipdb
        - matplotlib
        - catkin_pkg
        - seaborn
        - dominate
        - gitpython
        - ray
        - snakeviz
        - gtimer
# Can't get this to work, but you should install this if you want to run
# fanova analysis
#        - pyrfr
#        - git+https://github.com/automl/fanova.git
